author: 'Hingle' # 作者名称
author_avatar: 'https://sdn.geekzu.org/avatar/d22eb460ecab37fcd7205e6a3c55c228?s=200&r=X&d=' # 作者头像
author_text: '请在这里设置你的作者信息' # 作者信息
social: # 社交链接
  - title: 'Github'
    icon: 'github'
    link: 'https://github.com/Dreamer-Paul'
  - title: '首页'
    icon: 'home'
    link: 'https://paul.ren'
# background: 'https://api.paugram.com/wallpaper?source=gh' # 主题背景
menu: # 页眉菜单项目
  '关于我': /about
  '朋友们': /friends
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
